{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "btJf2NfXOjDo"
   },
   "source": [
    "\"\"\"\n",
    "================================================================================\n",
    "STUDENT INFORMATION\n",
    "================================================================================\n",
    "\n",
    "BITS ID: 2025AA05873\n",
    "Name: MANISH SINGHAL\n",
    "Email: 2025AA05873@WILP.BITS-PILANI.AC.IN\n",
    "Date: 14-02-2026\n",
    "\n",
    "===============\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "executionInfo": {
     "elapsed": 2048,
     "status": "ok",
     "timestamp": 1771059649275,
     "user": {
      "displayName": "MANISH SINGHAL",
      "userId": "13178962604892332050"
     },
     "user_tz": -330
    },
    "id": "mZj9dEDQNLUU"
   },
   "outputs": [],
   "source": [
    "# Import Required Libraries\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.preprocessing import StandardScaler, MinMaxScaler\n",
    "from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score\n",
    "import time\n",
    "import json\n",
    "import os\n",
    "import math\n",
    "import matplotlib.pyplot as plt\n",
    "from statsmodels.tsa.seasonal import seasonal_decompose\n",
    "from statsmodels.tsa.stattools import adfuller\n",
    "from sklearn.preprocessing import MinMaxScaler\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "executionInfo": {
     "elapsed": 19873,
     "status": "ok",
     "timestamp": 1771059669179,
     "user": {
      "displayName": "MANISH SINGHAL",
      "userId": "13178962604892332050"
     },
     "user_tz": -330
    },
    "id": "ktuaz4NMN88M",
    "outputId": "ab1e6db3-a0eb-4562-aaf6-296f014014f8"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Mounted at /content/drive\n",
      "['submission.csv', 'Screenshot-assignment1-2025aa05873.png', '2025aa05873.ipynb.ipynb', 'Colab Notebooks', 'CNN_Data', 'RNN_Data', 'ML_Assignment2_Data']\n",
      "['submission.csv', 'Screenshot-assignment1-2025aa05873.png', '2025aa05873.ipynb.ipynb', 'Colab Notebooks', 'CNN_Data', 'RNN_Data', 'ML_Assignment2_Data']\n",
      "['Credit_card_label.csv', 'Credit_card.csv']\n"
     ]
    }
   ],
   "source": [
    "from google.colab import drive\n",
    "\n",
    "# Mount Google Drive\n",
    "drive.mount('/content/drive')\n",
    "# List top-level contents of your Drive\n",
    "print(os.listdir(\"/content/drive/My Drive\"))\n",
    "# Drill down step by step\n",
    "print(os.listdir(\"/content/drive/My Drive/\"))\n",
    "print(os.listdir(\"/content/drive/My Drive/ML_Assignment2_Data\"))\n",
    "# Access files\n",
    "data_path = '/content/drive/My Drive/ML_Assignment2_Data/'\n",
    "\n",
    "#df = pd.read_csv(data_path)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "578a7d81"
   },
   "source": [
    "# Task\n",
    "Load the 'Credit_card.csv' and 'Credit_card_label.csv' datasets from \"/content/drive/My Drive/ML_Assignment2_Data/\", preprocess the data, build and train a Logistic Regression model, and then evaluate its performance using Accuracy, AUC Score, Precision, Recall, F1 Score, and Matthews Correlation Coefficient."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "be640c66"
   },
   "source": [
    "## Load Data\n",
    "\n",
    "### Subtask:\n",
    "Load 'Credit_card.csv' and 'Credit_card_label.csv' from the specified data path and merge them into a single DataFrame.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "ef4e71af"
   },
   "source": [
    "**Reasoning**:\n",
    "Load 'Credit_card.csv' and 'Credit_card_label.csv' into DataFrames and then merge them based on a common ID column.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "executionInfo": {
     "elapsed": 488,
     "status": "ok",
     "timestamp": 1771059669681,
     "user": {
      "displayName": "MANISH SINGHAL",
      "userId": "13178962604892332050"
     },
     "user_tz": -330
    },
    "id": "5affd249",
    "outputId": "766bc470-1e40-4d58-ce52-3a20bb71fe85"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "df_card head:\n",
      "    Ind_ID GENDER Car_Owner Propert_Owner  CHILDREN  Annual_income  \\\n",
      "0  5008827      M         Y             Y         0       180000.0   \n",
      "1  5009744      F         Y             N         0       315000.0   \n",
      "2  5009746      F         Y             N         0       315000.0   \n",
      "3  5009749      F         Y             N         0            NaN   \n",
      "4  5009752      F         Y             N         0       315000.0   \n",
      "\n",
      "            Type_Income         EDUCATION Marital_status       Housing_type  \\\n",
      "0             Pensioner  Higher education        Married  House / apartment   \n",
      "1  Commercial associate  Higher education        Married  House / apartment   \n",
      "2  Commercial associate  Higher education        Married  House / apartment   \n",
      "3  Commercial associate  Higher education        Married  House / apartment   \n",
      "4  Commercial associate  Higher education        Married  House / apartment   \n",
      "\n",
      "   Birthday_count  Employed_days  Mobile_phone  Work_Phone  Phone  EMAIL_ID  \\\n",
      "0        -18772.0         365243             1           0      0         0   \n",
      "1        -13557.0           -586             1           1      1         0   \n",
      "2             NaN           -586             1           1      1         0   \n",
      "3        -13557.0           -586             1           1      1         0   \n",
      "4        -13557.0           -586             1           1      1         0   \n",
      "\n",
      "  Type_Occupation  Family_Members  \n",
      "0             NaN               2  \n",
      "1             NaN               2  \n",
      "2             NaN               2  \n",
      "3             NaN               2  \n",
      "4             NaN               2  \n",
      "\n",
      "df_label head:\n",
      "    Ind_ID  label\n",
      "0  5008827      1\n",
      "1  5009744      1\n",
      "2  5009746      1\n",
      "3  5009749      1\n",
      "4  5009752      1\n",
      "\n",
      "Merged DataFrame head:\n",
      "    Ind_ID GENDER Car_Owner Propert_Owner  CHILDREN  Annual_income  \\\n",
      "0  5008827      M         Y             Y         0       180000.0   \n",
      "1  5009744      F         Y             N         0       315000.0   \n",
      "2  5009746      F         Y             N         0       315000.0   \n",
      "3  5009749      F         Y             N         0            NaN   \n",
      "4  5009752      F         Y             N         0       315000.0   \n",
      "\n",
      "            Type_Income         EDUCATION Marital_status       Housing_type  \\\n",
      "0             Pensioner  Higher education        Married  House / apartment   \n",
      "1  Commercial associate  Higher education        Married  House / apartment   \n",
      "2  Commercial associate  Higher education        Married  House / apartment   \n",
      "3  Commercial associate  Higher education        Married  House / apartment   \n",
      "4  Commercial associate  Higher education        Married  House / apartment   \n",
      "\n",
      "   Birthday_count  Employed_days  Mobile_phone  Work_Phone  Phone  EMAIL_ID  \\\n",
      "0        -18772.0         365243             1           0      0         0   \n",
      "1        -13557.0           -586             1           1      1         0   \n",
      "2             NaN           -586             1           1      1         0   \n",
      "3        -13557.0           -586             1           1      1         0   \n",
      "4        -13557.0           -586             1           1      1         0   \n",
      "\n",
      "  Type_Occupation  Family_Members  label  \n",
      "0             NaN               2      1  \n",
      "1             NaN               2      1  \n",
      "2             NaN               2      1  \n",
      "3             NaN               2      1  \n",
      "4             NaN               2      1  \n"
     ]
    }
   ],
   "source": [
    "df_card = pd.read_csv(data_path + 'Credit_card.csv')\n",
    "df_label = pd.read_csv(data_path + 'Credit_card_label.csv')\n",
    "\n",
    "# Merge the two dataframes\n",
    "df_merged = pd.merge(df_card, df_label, on='Ind_ID', how='inner')\n",
    "\n",
    "print(\"df_card head:\")\n",
    "print(df_card.head())\n",
    "print(\"\\ndf_label head:\")\n",
    "print(df_label.head())\n",
    "print(\"\\nMerged DataFrame head:\")\n",
    "print(df_merged.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 313
    },
    "executionInfo": {
     "elapsed": 58,
     "status": "ok",
     "timestamp": 1771059669744,
     "user": {
      "displayName": "MANISH SINGHAL",
      "userId": "13178962604892332050"
     },
     "user_tz": -330
    },
    "id": "6206a8c4",
    "outputId": "4952275a-61b8-4dab-c0ca-a6915414f45e"
   },
   "outputs": [
    {
     "data": {
      "application/vnd.google.colaboratory.intrinsic+json": {
       "repr_error": "Out of range float values are not JSON compliant: nan",
       "type": "dataframe"
      },
      "text/html": [
       "\n",
       "  <div id=\"df-f881eb7f-a527-4d70-9aa7-7f8acb81c239\" class=\"colab-df-container\">\n",
       "    <div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Ind_ID</th>\n",
       "      <th>GENDER</th>\n",
       "      <th>Car_Owner</th>\n",
       "      <th>Propert_Owner</th>\n",
       "      <th>CHILDREN</th>\n",
       "      <th>Annual_income</th>\n",
       "      <th>Type_Income</th>\n",
       "      <th>EDUCATION</th>\n",
       "      <th>Marital_status</th>\n",
       "      <th>Housing_type</th>\n",
       "      <th>Birthday_count</th>\n",
       "      <th>Employed_days</th>\n",
       "      <th>Mobile_phone</th>\n",
       "      <th>Work_Phone</th>\n",
       "      <th>Phone</th>\n",
       "      <th>EMAIL_ID</th>\n",
       "      <th>Type_Occupation</th>\n",
       "      <th>Family_Members</th>\n",
       "      <th>label</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>5008827</td>\n",
       "      <td>M</td>\n",
       "      <td>Y</td>\n",
       "      <td>Y</td>\n",
       "      <td>0</td>\n",
       "      <td>180000.0</td>\n",
       "      <td>Pensioner</td>\n",
       "      <td>Higher education</td>\n",
       "      <td>Married</td>\n",
       "      <td>House / apartment</td>\n",
       "      <td>-18772.0</td>\n",
       "      <td>365243</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>5009744</td>\n",
       "      <td>F</td>\n",
       "      <td>Y</td>\n",
       "      <td>N</td>\n",
       "      <td>0</td>\n",
       "      <td>315000.0</td>\n",
       "      <td>Commercial associate</td>\n",
       "      <td>Higher education</td>\n",
       "      <td>Married</td>\n",
       "      <td>House / apartment</td>\n",
       "      <td>-13557.0</td>\n",
       "      <td>-586</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>5009746</td>\n",
       "      <td>F</td>\n",
       "      <td>Y</td>\n",
       "      <td>N</td>\n",
       "      <td>0</td>\n",
       "      <td>315000.0</td>\n",
       "      <td>Commercial associate</td>\n",
       "      <td>Higher education</td>\n",
       "      <td>Married</td>\n",
       "      <td>House / apartment</td>\n",
       "      <td>NaN</td>\n",
       "      <td>-586</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>5009749</td>\n",
       "      <td>F</td>\n",
       "      <td>Y</td>\n",
       "      <td>N</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Commercial associate</td>\n",
       "      <td>Higher education</td>\n",
       "      <td>Married</td>\n",
       "      <td>House / apartment</td>\n",
       "      <td>-13557.0</td>\n",
       "      <td>-586</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5009752</td>\n",
       "      <td>F</td>\n",
       "      <td>Y</td>\n",
       "      <td>N</td>\n",
       "      <td>0</td>\n",
       "      <td>315000.0</td>\n",
       "      <td>Commercial associate</td>\n",
       "      <td>Higher education</td>\n",
       "      <td>Married</td>\n",
       "      <td>House / apartment</td>\n",
       "      <td>-13557.0</td>\n",
       "      <td>-586</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>\n",
       "    <div class=\"colab-df-buttons\">\n",
       "\n",
       "  <div class=\"colab-df-container\">\n",
       "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-f881eb7f-a527-4d70-9aa7-7f8acb81c239')\"\n",
       "            title=\"Convert this dataframe to an interactive table.\"\n",
       "            style=\"display:none;\">\n",
       "\n",
       "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
       "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
       "  </svg>\n",
       "    </button>\n",
       "\n",
       "  <style>\n",
       "    .colab-df-container {\n",
       "      display:flex;\n",
       "      gap: 12px;\n",
       "    }\n",
       "\n",
       "    .colab-df-convert {\n",
       "      background-color: #E8F0FE;\n",
       "      border: none;\n",
       "      border-radius: 50%;\n",
       "      cursor: pointer;\n",
       "      display: none;\n",
       "      fill: #1967D2;\n",
       "      height: 32px;\n",
       "      padding: 0 0 0 0;\n",
       "      width: 32px;\n",
       "    }\n",
       "\n",
       "    .colab-df-convert:hover {\n",
       "      background-color: #E2EBFA;\n",
       "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
       "      fill: #174EA6;\n",
       "    }\n",
       "\n",
       "    .colab-df-buttons div {\n",
       "      margin-bottom: 4px;\n",
       "    }\n",
       "\n",
       "    [theme=dark] .colab-df-convert {\n",
       "      background-color: #3B4455;\n",
       "      fill: #D2E3FC;\n",
       "    }\n",
       "\n",
       "    [theme=dark] .colab-df-convert:hover {\n",
       "      background-color: #434B5C;\n",
       "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
       "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
       "      fill: #FFFFFF;\n",
       "    }\n",
       "  </style>\n",
       "\n",
       "    <script>\n",
       "      const buttonEl =\n",
       "        document.querySelector('#df-f881eb7f-a527-4d70-9aa7-7f8acb81c239 button.colab-df-convert');\n",
       "      buttonEl.style.display =\n",
       "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
       "\n",
       "      async function convertToInteractive(key) {\n",
       "        const element = document.querySelector('#df-f881eb7f-a527-4d70-9aa7-7f8acb81c239');\n",
       "        const dataTable =\n",
       "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
       "                                                    [key], {});\n",
       "        if (!dataTable) return;\n",
       "\n",
       "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
       "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
       "          + ' to learn more about interactive tables.';\n",
       "        element.innerHTML = '';\n",
       "        dataTable['output_type'] = 'display_data';\n",
       "        await google.colab.output.renderOutput(dataTable, element);\n",
       "        const docLink = document.createElement('div');\n",
       "        docLink.innerHTML = docLinkHtml;\n",
       "        element.appendChild(docLink);\n",
       "      }\n",
       "    </script>\n",
       "  </div>\n",
       "\n",
       "\n",
       "    </div>\n",
       "  </div>\n"
      ],
      "text/plain": [
       "    Ind_ID GENDER Car_Owner Propert_Owner  CHILDREN  Annual_income  \\\n",
       "0  5008827      M         Y             Y         0       180000.0   \n",
       "1  5009744      F         Y             N         0       315000.0   \n",
       "2  5009746      F         Y             N         0       315000.0   \n",
       "3  5009749      F         Y             N         0            NaN   \n",
       "4  5009752      F         Y             N         0       315000.0   \n",
       "\n",
       "            Type_Income         EDUCATION Marital_status       Housing_type  \\\n",
       "0             Pensioner  Higher education        Married  House / apartment   \n",
       "1  Commercial associate  Higher education        Married  House / apartment   \n",
       "2  Commercial associate  Higher education        Married  House / apartment   \n",
       "3  Commercial associate  Higher education        Married  House / apartment   \n",
       "4  Commercial associate  Higher education        Married  House / apartment   \n",
       "\n",
       "   Birthday_count  Employed_days  Mobile_phone  Work_Phone  Phone  EMAIL_ID  \\\n",
       "0        -18772.0         365243             1           0      0         0   \n",
       "1        -13557.0           -586             1           1      1         0   \n",
       "2             NaN           -586             1           1      1         0   \n",
       "3        -13557.0           -586             1           1      1         0   \n",
       "4        -13557.0           -586             1           1      1         0   \n",
       "\n",
       "  Type_Occupation  Family_Members  label  \n",
       "0             NaN               2      1  \n",
       "1             NaN               2      1  \n",
       "2             NaN               2      1  \n",
       "3             NaN               2      1  \n",
       "4             NaN               2      1  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "display(df_merged.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "executionInfo": {
     "elapsed": 35,
     "status": "ok",
     "timestamp": 1771059669788,
     "user": {
      "displayName": "MANISH SINGHAL",
      "userId": "13178962604892332050"
     },
     "user_tz": -330
    },
    "id": "84a5540c",
    "outputId": "c2017005-3281-40c4-835c-cdef70d566f1"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "df_card head:\n",
      "    Ind_ID GENDER Car_Owner Propert_Owner  CHILDREN  Annual_income  \\\n",
      "0  5008827      M         Y             Y         0       180000.0   \n",
      "1  5009744      F         Y             N         0       315000.0   \n",
      "2  5009746      F         Y             N         0       315000.0   \n",
      "3  5009749      F         Y             N         0            NaN   \n",
      "4  5009752      F         Y             N         0       315000.0   \n",
      "\n",
      "            Type_Income         EDUCATION Marital_status       Housing_type  \\\n",
      "0             Pensioner  Higher education        Married  House / apartment   \n",
      "1  Commercial associate  Higher education        Married  House / apartment   \n",
      "2  Commercial associate  Higher education        Married  House / apartment   \n",
      "3  Commercial associate  Higher education        Married  House / apartment   \n",
      "4  Commercial associate  Higher education        Married  House / apartment   \n",
      "\n",
      "   Birthday_count  Employed_days  Mobile_phone  Work_Phone  Phone  EMAIL_ID  \\\n",
      "0        -18772.0         365243             1           0      0         0   \n",
      "1        -13557.0           -586             1           1      1         0   \n",
      "2             NaN           -586             1           1      1         0   \n",
      "3        -13557.0           -586             1           1      1         0   \n",
      "4        -13557.0           -586             1           1      1         0   \n",
      "\n",
      "  Type_Occupation  Family_Members  \n",
      "0             NaN               2  \n",
      "1             NaN               2  \n",
      "2             NaN               2  \n",
      "3             NaN               2  \n",
      "4             NaN               2  \n",
      "\n",
      "df_label head:\n",
      "    Ind_ID  label\n",
      "0  5008827      1\n",
      "1  5009744      1\n",
      "2  5009746      1\n",
      "3  5009749      1\n",
      "4  5009752      1\n",
      "\n",
      "Merged DataFrame head:\n",
      "    Ind_ID GENDER Car_Owner Propert_Owner  CHILDREN  Annual_income  \\\n",
      "0  5008827      M         Y             Y         0       180000.0   \n",
      "1  5009744      F         Y             N         0       315000.0   \n",
      "2  5009746      F         Y             N         0       315000.0   \n",
      "3  5009749      F         Y             N         0            NaN   \n",
      "4  5009752      F         Y             N         0       315000.0   \n",
      "\n",
      "            Type_Income         EDUCATION Marital_status       Housing_type  \\\n",
      "0             Pensioner  Higher education        Married  House / apartment   \n",
      "1  Commercial associate  Higher education        Married  House / apartment   \n",
      "2  Commercial associate  Higher education        Married  House / apartment   \n",
      "3  Commercial associate  Higher education        Married  House / apartment   \n",
      "4  Commercial associate  Higher education        Married  House / apartment   \n",
      "\n",
      "   Birthday_count  Employed_days  Mobile_phone  Work_Phone  Phone  EMAIL_ID  \\\n",
      "0        -18772.0         365243             1           0      0         0   \n",
      "1        -13557.0           -586             1           1      1         0   \n",
      "2             NaN           -586             1           1      1         0   \n",
      "3        -13557.0           -586             1           1      1         0   \n",
      "4        -13557.0           -586             1           1      1         0   \n",
      "\n",
      "  Type_Occupation  Family_Members  label  \n",
      "0             NaN               2      1  \n",
      "1             NaN               2      1  \n",
      "2             NaN               2      1  \n",
      "3             NaN               2      1  \n",
      "4             NaN               2      1  \n"
     ]
    }
   ],
   "source": [
    "df_card = pd.read_csv(data_path + 'Credit_card.csv')\n",
    "df_label = pd.read_csv(data_path + 'Credit_card_label.csv')\n",
    "\n",
    "# Merge the two dataframes\n",
    "df_merged = pd.merge(df_card, df_label, on='Ind_ID', how='inner')\n",
    "\n",
    "print(\"df_card head:\")\n",
    "print(df_card.head())\n",
    "print(\"\\ndf_label head:\")\n",
    "print(df_label.head())\n",
    "print(\"\\nMerged DataFrame head:\")\n",
    "print(df_merged.head())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "bb9739ba"
   },
   "source": [
    "## Data Preprocessing\n",
    "\n",
    "### Subtask:\n",
    "Inspect the merged dataset, handle any missing values, encode categorical features, split the data into features (X) and target (y), and then split X and y into training and testing sets. Finally, scale numerical features using StandardScaler.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "01d2409b"
   },
   "source": [
    "\n",
    "To inspect the merged dataset to understand its structure, data types, and identify missing values and categorical features.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 1000
    },
    "executionInfo": {
     "elapsed": 53,
     "status": "ok",
     "timestamp": 1771059669840,
     "user": {
      "displayName": "MANISH SINGHAL",
      "userId": "13178962604892332050"
     },
     "user_tz": -330
    },
    "id": "403435c3",
    "outputId": "9ff04743-06e5-4e8d-cc26-2c996627102b"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "DataFrame Info:\n",
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 1548 entries, 0 to 1547\n",
      "Data columns (total 19 columns):\n",
      " #   Column           Non-Null Count  Dtype  \n",
      "---  ------           --------------  -----  \n",
      " 0   Ind_ID           1548 non-null   int64  \n",
      " 1   GENDER           1541 non-null   object \n",
      " 2   Car_Owner        1548 non-null   object \n",
      " 3   Propert_Owner    1548 non-null   object \n",
      " 4   CHILDREN         1548 non-null   int64  \n",
      " 5   Annual_income    1525 non-null   float64\n",
      " 6   Type_Income      1548 non-null   object \n",
      " 7   EDUCATION        1548 non-null   object \n",
      " 8   Marital_status   1548 non-null   object \n",
      " 9   Housing_type     1548 non-null   object \n",
      " 10  Birthday_count   1526 non-null   float64\n",
      " 11  Employed_days    1548 non-null   int64  \n",
      " 12  Mobile_phone     1548 non-null   int64  \n",
      " 13  Work_Phone       1548 non-null   int64  \n",
      " 14  Phone            1548 non-null   int64  \n",
      " 15  EMAIL_ID         1548 non-null   int64  \n",
      " 16  Type_Occupation  1060 non-null   object \n",
      " 17  Family_Members   1548 non-null   int64  \n",
      " 18  label            1548 non-null   int64  \n",
      "dtypes: float64(2), int64(9), object(8)\n",
      "memory usage: 229.9+ KB\n",
      "\n",
      "Descriptive Statistics (all columns):\n",
      "\n",
      "Missing values per column:\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>0</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Ind_ID</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>GENDER</th>\n",
       "      <td>7</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Car_Owner</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Propert_Owner</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>CHILDREN</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Annual_income</th>\n",
       "      <td>23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Type_Income</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>EDUCATION</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Marital_status</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Housing_type</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Birthday_count</th>\n",
       "      <td>22</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Employed_days</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Mobile_phone</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Work_Phone</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Phone</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>EMAIL_ID</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Type_Occupation</th>\n",
       "      <td>488</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Family_Members</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>label</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div><br><label><b>dtype:</b> int64</label>"
      ],
      "text/plain": [
       "Ind_ID               0\n",
       "GENDER               7\n",
       "Car_Owner            0\n",
       "Propert_Owner        0\n",
       "CHILDREN             0\n",
       "Annual_income       23\n",
       "Type_Income          0\n",
       "EDUCATION            0\n",
       "Marital_status       0\n",
       "Housing_type         0\n",
       "Birthday_count      22\n",
       "Employed_days        0\n",
       "Mobile_phone         0\n",
       "Work_Phone           0\n",
       "Phone                0\n",
       "EMAIL_ID             0\n",
       "Type_Occupation    488\n",
       "Family_Members       0\n",
       "label                0\n",
       "dtype: int64"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "print(\"DataFrame Info:\")\n",
    "df_merged.info()\n",
    "\n",
    "print(\"\\nDescriptive Statistics (all columns):\")\n",
    "df_merged.describe(include='all')\n",
    "\n",
    "print(\"\\nMissing values per column:\")\n",
    "df_merged.isnull().sum()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "3466d72a"
   },
   "source": [
    "\n",
    "Based on the inspection,  missing values are handled by imputing categorical columns (`GENDER`, `Type_Occupation`) with their respective modes and numerical columns (`Annual_income`, `Birthday_count`) with their medians to maintain data integrity and prevent data loss.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "executionInfo": {
     "elapsed": 132,
     "status": "ok",
     "timestamp": 1771059669972,
     "user": {
      "displayName": "MANISH SINGHAL",
      "userId": "13178962604892332050"
     },
     "user_tz": -330
    },
    "id": "060f4d19",
    "outputId": "010a9f05-f634-4913-b31a-70be580fd279"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Missing values before imputation:\n",
      "GENDER               7\n",
      "Annual_income       23\n",
      "Birthday_count      22\n",
      "Type_Occupation    488\n",
      "dtype: int64\n",
      "\n",
      "Missing values after imputation:\n",
      "Series([], dtype: int64)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipython-input-29408162.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.\n",
      "The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.\n",
      "\n",
      "For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.\n",
      "\n",
      "\n",
      "  df_merged['GENDER'].fillna(df_merged['GENDER'].mode()[0], inplace=True)\n",
      "/tmp/ipython-input-29408162.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.\n",
      "The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.\n",
      "\n",
      "For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.\n",
      "\n",
      "\n",
      "  df_merged['Annual_income'].fillna(df_merged['Annual_income'].median(), inplace=True)\n",
      "/tmp/ipython-input-29408162.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.\n",
      "The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.\n",
      "\n",
      "For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.\n",
      "\n",
      "\n",
      "  df_merged['Birthday_count'].fillna(df_merged['Birthday_count'].median(), inplace=True)\n",
      "/tmp/ipython-input-29408162.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.\n",
      "The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.\n",
      "\n",
      "For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.\n",
      "\n",
      "\n",
      "  df_merged['Type_Occupation'].fillna(df_merged['Type_Occupation'].mode()[0], inplace=True)\n"
     ]
    }
   ],
   "source": [
    "print(\"Missing values before imputation:\")\n",
    "print(df_merged.isnull().sum()[df_merged.isnull().sum() > 0])\n",
    "\n",
    "# Impute GENDER with mode\n",
    "df_merged['GENDER'].fillna(df_merged['GENDER'].mode()[0], inplace=True)\n",
    "\n",
    "# Impute Annual_income with median\n",
    "df_merged['Annual_income'].fillna(df_merged['Annual_income'].median(), inplace=True)\n",
    "\n",
    "# Impute Birthday_count with median\n",
    "df_merged['Birthday_count'].fillna(df_merged['Birthday_count'].median(), inplace=True)\n",
    "\n",
    "# Impute Type_Occupation with mode\n",
    "df_merged['Type_Occupation'].fillna(df_merged['Type_Occupation'].mode()[0], inplace=True)\n",
    "\n",
    "print(\"\\nMissing values after imputation:\")\n",
    "print(df_merged.isnull().sum()[df_merged.isnull().sum() > 0])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "executionInfo": {
     "elapsed": 21,
     "status": "ok",
     "timestamp": 1771059669974,
     "user": {
      "displayName": "MANISH SINGHAL",
      "userId": "13178962604892332050"
     },
     "user_tz": -330
    },
    "id": "acffb941",
    "outputId": "65572654-b1e7-463a-a178-07b6163c9772"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Missing values before imputation:\n",
      "Series([], dtype: int64)\n",
      "\n",
      "Missing values after imputation:\n",
      "Series([], dtype: int64)\n"
     ]
    }
   ],
   "source": [
    "print(\"Missing values before imputation:\")\n",
    "print(df_merged.isnull().sum()[df_merged.isnull().sum() > 0])\n",
    "\n",
    "# Impute GENDER with mode\n",
    "df_merged['GENDER'] = df_merged['GENDER'].fillna(df_merged['GENDER'].mode()[0])\n",
    "\n",
    "# Impute Annual_income with median\n",
    "df_merged['Annual_income'] = df_merged['Annual_income'].fillna(df_merged['Annual_income'].median())\n",
    "\n",
    "# Impute Birthday_count with median\n",
    "df_merged['Birthday_count'] = df_merged['Birthday_count'].fillna(df_merged['Birthday_count'].median())\n",
    "\n",
    "# Impute Type_Occupation with mode\n",
    "df_merged['Type_Occupation'] = df_merged['Type_Occupation'].fillna(df_merged['Type_Occupation'].mode()[0])\n",
    "\n",
    "print(\"\\nMissing values after imputation:\")\n",
    "print(df_merged.isnull().sum()[df_merged.isnull().sum() > 0])"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "7a81d728"
   },
   "source": [
    "\n",
    "Now that missing values have been handled, I will identify categorical columns and apply one-hot encoding to convert them into numerical format, which is required for most machine learning models. The 'Ind_ID' column will be excluded as it's an identifier, and the 'label' column will be excluded as it's the target variable.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "executionInfo": {
     "elapsed": 23,
     "status": "ok",
     "timestamp": 1771059669993,
     "user": {
      "displayName": "MANISH SINGHAL",
      "userId": "13178962604892332050"
     },
     "user_tz": -330
    },
    "id": "9432d1b8",
    "outputId": "567fc8bd-07c7-464f-a69d-8c877862c33a"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Original DataFrame columns and data types:\n",
      "Ind_ID               int64\n",
      "GENDER              object\n",
      "Car_Owner           object\n",
      "Propert_Owner       object\n",
      "CHILDREN             int64\n",
      "Annual_income      float64\n",
      "Type_Income         object\n",
      "EDUCATION           object\n",
      "Marital_status      object\n",
      "Housing_type        object\n",
      "Birthday_count     float64\n",
      "Employed_days        int64\n",
      "Mobile_phone         int64\n",
      "Work_Phone           int64\n",
      "Phone                int64\n",
      "EMAIL_ID             int64\n",
      "Type_Occupation     object\n",
      "Family_Members       int64\n",
      "label                int64\n",
      "dtype: object\n",
      "\n",
      "Categorical columns to encode: ['GENDER', 'Car_Owner', 'Propert_Owner', 'Type_Income', 'EDUCATION', 'Marital_status', 'Housing_type', 'Type_Occupation']\n",
      "\n",
      "DataFrame head after one-hot encoding:\n",
      "    Ind_ID  CHILDREN  Annual_income  Birthday_count  Employed_days  \\\n",
      "0  5008827         0       180000.0        -18772.0         365243   \n",
      "1  5009744         0       315000.0        -13557.0           -586   \n",
      "2  5009746         0       315000.0        -15661.5           -586   \n",
      "3  5009749         0       166500.0        -13557.0           -586   \n",
      "4  5009752         0       315000.0        -13557.0           -586   \n",
      "\n",
      "   Mobile_phone  Work_Phone  Phone  EMAIL_ID  Family_Members  ...  \\\n",
      "0             1           0      0         0               2  ...   \n",
      "1             1           1      1         0               2  ...   \n",
      "2             1           1      1         0               2  ...   \n",
      "3             1           1      1         0               2  ...   \n",
      "4             1           1      1         0               2  ...   \n",
      "\n",
      "   Type_Occupation_Laborers  Type_Occupation_Low-skill Laborers  \\\n",
      "0                      True                               False   \n",
      "1                      True                               False   \n",
      "2                      True                               False   \n",
      "3                      True                               False   \n",
      "4                      True                               False   \n",
      "\n",
      "   Type_Occupation_Managers  Type_Occupation_Medicine staff  \\\n",
      "0                     False                           False   \n",
      "1                     False                           False   \n",
      "2                     False                           False   \n",
      "3                     False                           False   \n",
      "4                     False                           False   \n",
      "\n",
      "   Type_Occupation_Private service staff  Type_Occupation_Realty agents  \\\n",
      "0                                  False                          False   \n",
      "1                                  False                          False   \n",
      "2                                  False                          False   \n",
      "3                                  False                          False   \n",
      "4                                  False                          False   \n",
      "\n",
      "   Type_Occupation_Sales staff  Type_Occupation_Secretaries  \\\n",
      "0                        False                        False   \n",
      "1                        False                        False   \n",
      "2                        False                        False   \n",
      "3                        False                        False   \n",
      "4                        False                        False   \n",
      "\n",
      "   Type_Occupation_Security staff  Type_Occupation_Waiters/barmen staff  \n",
      "0                           False                                 False  \n",
      "1                           False                                 False  \n",
      "2                           False                                 False  \n",
      "3                           False                                 False  \n",
      "4                           False                                 False  \n",
      "\n",
      "[5 rows x 47 columns]\n",
      "\n",
      "DataFrame info after one-hot encoding:\n",
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 1548 entries, 0 to 1547\n",
      "Data columns (total 47 columns):\n",
      " #   Column                                   Non-Null Count  Dtype  \n",
      "---  ------                                   --------------  -----  \n",
      " 0   Ind_ID                                   1548 non-null   int64  \n",
      " 1   CHILDREN                                 1548 non-null   int64  \n",
      " 2   Annual_income                            1548 non-null   float64\n",
      " 3   Birthday_count                           1548 non-null   float64\n",
      " 4   Employed_days                            1548 non-null   int64  \n",
      " 5   Mobile_phone                             1548 non-null   int64  \n",
      " 6   Work_Phone                               1548 non-null   int64  \n",
      " 7   Phone                                    1548 non-null   int64  \n",
      " 8   EMAIL_ID                                 1548 non-null   int64  \n",
      " 9   Family_Members                           1548 non-null   int64  \n",
      " 10  label                                    1548 non-null   int64  \n",
      " 11  GENDER_M                                 1548 non-null   bool   \n",
      " 12  Car_Owner_Y                              1548 non-null   bool   \n",
      " 13  Propert_Owner_Y                          1548 non-null   bool   \n",
      " 14  Type_Income_Pensioner                    1548 non-null   bool   \n",
      " 15  Type_Income_State servant                1548 non-null   bool   \n",
      " 16  Type_Income_Working                      1548 non-null   bool   \n",
      " 17  EDUCATION_Higher education               1548 non-null   bool   \n",
      " 18  EDUCATION_Incomplete higher              1548 non-null   bool   \n",
      " 19  EDUCATION_Lower secondary                1548 non-null   bool   \n",
      " 20  EDUCATION_Secondary / secondary special  1548 non-null   bool   \n",
      " 21  Marital_status_Married                   1548 non-null   bool   \n",
      " 22  Marital_status_Separated                 1548 non-null   bool   \n",
      " 23  Marital_status_Single / not married      1548 non-null   bool   \n",
      " 24  Marital_status_Widow                     1548 non-null   bool   \n",
      " 25  Housing_type_House / apartment           1548 non-null   bool   \n",
      " 26  Housing_type_Municipal apartment         1548 non-null   bool   \n",
      " 27  Housing_type_Office apartment            1548 non-null   bool   \n",
      " 28  Housing_type_Rented apartment            1548 non-null   bool   \n",
      " 29  Housing_type_With parents                1548 non-null   bool   \n",
      " 30  Type_Occupation_Cleaning staff           1548 non-null   bool   \n",
      " 31  Type_Occupation_Cooking staff            1548 non-null   bool   \n",
      " 32  Type_Occupation_Core staff               1548 non-null   bool   \n",
      " 33  Type_Occupation_Drivers                  1548 non-null   bool   \n",
      " 34  Type_Occupation_HR staff                 1548 non-null   bool   \n",
      " 35  Type_Occupation_High skill tech staff    1548 non-null   bool   \n",
      " 36  Type_Occupation_IT staff                 1548 non-null   bool   \n",
      " 37  Type_Occupation_Laborers                 1548 non-null   bool   \n",
      " 38  Type_Occupation_Low-skill Laborers       1548 non-null   bool   \n",
      " 39  Type_Occupation_Managers                 1548 non-null   bool   \n",
      " 40  Type_Occupation_Medicine staff           1548 non-null   bool   \n",
      " 41  Type_Occupation_Private service staff    1548 non-null   bool   \n",
      " 42  Type_Occupation_Realty agents            1548 non-null   bool   \n",
      " 43  Type_Occupation_Sales staff              1548 non-null   bool   \n",
      " 44  Type_Occupation_Secretaries              1548 non-null   bool   \n",
      " 45  Type_Occupation_Security staff           1548 non-null   bool   \n",
      " 46  Type_Occupation_Waiters/barmen staff     1548 non-null   bool   \n",
      "dtypes: bool(36), float64(2), int64(9)\n",
      "memory usage: 187.6 KB\n"
     ]
    }
   ],
   "source": [
    "print(\"Original DataFrame columns and data types:\")\n",
    "print(df_merged.dtypes)\n",
    "\n",
    "# Identify categorical columns (excluding 'Ind_ID' and 'label')\n",
    "categorical_cols = df_merged.select_dtypes(include='object').columns.tolist()\n",
    "\n",
    "# Exclude 'Ind_ID' as it's an identifier and 'label' as it's the target\n",
    "if 'Ind_ID' in categorical_cols:\n",
    "    categorical_cols.remove('Ind_ID')\n",
    "if 'label' in categorical_cols:\n",
    "    categorical_cols.remove('label')\n",
    "\n",
    "print(f\"\\nCategorical columns to encode: {categorical_cols}\")\n",
    "\n",
    "# Apply one-hot encoding\n",
    "df_encoded = pd.get_dummies(df_merged, columns=categorical_cols, drop_first=True)\n",
    "\n",
    "print(\"\\nDataFrame head after one-hot encoding:\")\n",
    "print(df_encoded.head())\n",
    "print(\"\\nDataFrame info after one-hot encoding:\")\n",
    "df_encoded.info()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "a3890f65"
   },
   "source": [
    "\n",
    "Now that categorical features are encoded, I will separate the DataFrame into features (X) and the target variable (y). The 'label' column is the target, and the 'Ind_ID' column will be dropped from the features as it's an identifier and not relevant for model training.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "executionInfo": {
     "elapsed": 20,
     "status": "ok",
     "timestamp": 1771059670015,
     "user": {
      "displayName": "MANISH SINGHAL",
      "userId": "13178962604892332050"
     },
     "user_tz": -330
    },
    "id": "9375b245",
    "outputId": "a56b02f3-def5-4b5c-b53b-ec7209420cc3"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Features (X) head:\n",
      "   CHILDREN  Annual_income  Birthday_count  Employed_days  Mobile_phone  \\\n",
      "0         0       180000.0        -18772.0         365243             1   \n",
      "1         0       315000.0        -13557.0           -586             1   \n",
      "2         0       315000.0        -15661.5           -586             1   \n",
      "3         0       166500.0        -13557.0           -586             1   \n",
      "4         0       315000.0        -13557.0           -586             1   \n",
      "\n",
      "   Work_Phone  Phone  EMAIL_ID  Family_Members  GENDER_M  ...  \\\n",
      "0           0      0         0               2      True  ...   \n",
      "1           1      1         0               2     False  ...   \n",
      "2           1      1         0               2     False  ...   \n",
      "3           1      1         0               2     False  ...   \n",
      "4           1      1         0               2     False  ...   \n",
      "\n",
      "   Type_Occupation_Laborers  Type_Occupation_Low-skill Laborers  \\\n",
      "0                      True                               False   \n",
      "1                      True                               False   \n",
      "2                      True                               False   \n",
      "3                      True                               False   \n",
      "4                      True                               False   \n",
      "\n",
      "   Type_Occupation_Managers  Type_Occupation_Medicine staff  \\\n",
      "0                     False                           False   \n",
      "1                     False                           False   \n",
      "2                     False                           False   \n",
      "3                     False                           False   \n",
      "4                     False                           False   \n",
      "\n",
      "   Type_Occupation_Private service staff  Type_Occupation_Realty agents  \\\n",
      "0                                  False                          False   \n",
      "1                                  False                          False   \n",
      "2                                  False                          False   \n",
      "3                                  False                          False   \n",
      "4                                  False                          False   \n",
      "\n",
      "   Type_Occupation_Sales staff  Type_Occupation_Secretaries  \\\n",
      "0                        False                        False   \n",
      "1                        False                        False   \n",
      "2                        False                        False   \n",
      "3                        False                        False   \n",
      "4                        False                        False   \n",
      "\n",
      "   Type_Occupation_Security staff  Type_Occupation_Waiters/barmen staff  \n",
      "0                           False                                 False  \n",
      "1                           False                                 False  \n",
      "2                           False                                 False  \n",
      "3                           False                                 False  \n",
      "4                           False                                 False  \n",
      "\n",
      "[5 rows x 45 columns]\n",
      "\n",
      "Target (y) head:\n",
      "0    1\n",
      "1    1\n",
      "2    1\n",
      "3    1\n",
      "4    1\n",
      "Name: label, dtype: int64\n"
     ]
    }
   ],
   "source": [
    "X = df_encoded.drop(columns=['label', 'Ind_ID'])\n",
    "y = df_encoded['label']\n",
    "\n",
    "print(\"Features (X) head:\")\n",
    "print(X.head())\n",
    "print(\"\\nTarget (y) head:\")\n",
    "print(y.head())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "e0c6a6d6"
   },
   "source": [
    " split the data into training and testing sets using `train_test_split` with a test size of 0.2 and a `random_state` of 42 for reproducibility, as per the subtask instructions.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "executionInfo": {
     "elapsed": 11,
     "status": "ok",
     "timestamp": 1771059670022,
     "user": {
      "displayName": "MANISH SINGHAL",
      "userId": "13178962604892332050"
     },
     "user_tz": -330
    },
    "id": "22510ea6",
    "outputId": "caff923f-3917-4218-e22e-c1ac981c3293"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "X_train shape: (1238, 45)\n",
      "X_test shape: (310, 45)\n",
      "y_train shape: (1238,)\n",
      "y_test shape: (310,)\n"
     ]
    }
   ],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)\n",
    "\n",
    "print(\"X_train shape:\", X_train.shape)\n",
    "print(\"X_test shape:\", X_test.shape)\n",
    "print(\"y_train shape:\", y_train.shape)\n",
    "print(\"y_test shape:\", y_test.shape)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "e3dfa550"
   },
   "source": [
    "scale the numerical features in both the training and testing sets using `StandardScaler`. I will fit the scaler only on the training data (`X_train`) to prevent data leakage and then transform both `X_train` and `X_test`.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "executionInfo": {
     "elapsed": 22,
     "status": "ok",
     "timestamp": 1771059670045,
     "user": {
      "displayName": "MANISH SINGHAL",
      "userId": "13178962604892332050"
     },
     "user_tz": -330
    },
    "id": "30d54bdf",
    "outputId": "e81b5511-2e0d-48b1-97c7-1e5a9448de2a"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "X_train head after scaling numerical features:\n",
      "      CHILDREN  Annual_income  Birthday_count  Employed_days  Mobile_phone  \\\n",
      "310  -0.531533      -0.475814       -0.274053      -0.445640           0.0   \n",
      "1484 -0.531533      -0.475814        0.903874      -0.444296           0.0   \n",
      "1210 -0.531533      -0.672072        1.337051      -0.452029           0.0   \n",
      "829  -0.531533      -0.083297        0.452245      -0.453207           0.0   \n",
      "53    0.710048      -0.475814        1.514485      -0.439982           0.0   \n",
      "\n",
      "      Work_Phone     Phone  EMAIL_ID  Family_Members  GENDER_M  ...  \\\n",
      "310    -0.509323 -0.655409 -0.315384       -0.171436      True  ...   \n",
      "1484    1.963390 -0.655409 -0.315384       -0.171436     False  ...   \n",
      "1210   -0.509323 -0.655409 -0.315384       -0.171436     False  ...   \n",
      "829     1.963390 -0.655409 -0.315384       -0.171436      True  ...   \n",
      "53     -0.509323 -0.655409 -0.315384        0.848939      True  ...   \n",
      "\n",
      "      Type_Occupation_Laborers  Type_Occupation_Low-skill Laborers  \\\n",
      "310                      False                               False   \n",
      "1484                     False                               False   \n",
      "1210                      True                               False   \n",
      "829                      False                               False   \n",
      "53                        True                               False   \n",
      "\n",
      "      Type_Occupation_Managers  Type_Occupation_Medicine staff  \\\n",
      "310                      False                           False   \n",
      "1484                     False                           False   \n",
      "1210                     False                           False   \n",
      "829                      False                           False   \n",
      "53                       False                           False   \n",
      "\n",
      "      Type_Occupation_Private service staff  Type_Occupation_Realty agents  \\\n",
      "310                                   False                          False   \n",
      "1484                                  False                          False   \n",
      "1210                                  False                          False   \n",
      "829                                   False                          False   \n",
      "53                                    False                          False   \n",
      "\n",
      "      Type_Occupation_Sales staff  Type_Occupation_Secretaries  \\\n",
      "310                         False                        False   \n",
      "1484                        False                        False   \n",
      "1210                        False                        False   \n",
      "829                         False                        False   \n",
      "53                          False                        False   \n",
      "\n",
      "      Type_Occupation_Security staff  Type_Occupation_Waiters/barmen staff  \n",
      "310                            False                                 False  \n",
      "1484                           False                                 False  \n",
      "1210                           False                                 False  \n",
      "829                            False                                 False  \n",
      "53                             False                                 False  \n",
      "\n",
      "[5 rows x 45 columns]\n",
      "\n",
      "X_test head after scaling numerical features:\n",
      "      CHILDREN  Annual_income  Birthday_count  Employed_days  Mobile_phone  \\\n",
      "1545  1.951629      -0.083297        0.667532      -0.451624           0.0   \n",
      "1203 -0.531533       0.191464       -0.296528      -0.445727           0.0   \n",
      "1311 -0.531533       0.309219        1.009625      -0.440459           0.0   \n",
      "1234 -0.531533      -0.672072       -0.740351       2.205910           0.0   \n",
      "725  -0.531533      -0.083297       -1.226521      -0.453438           0.0   \n",
      "\n",
      "      Work_Phone     Phone  EMAIL_ID  Family_Members  GENDER_M  ...  \\\n",
      "1545   -0.509323 -0.655409 -0.315384        1.869313      True  ...   \n",
      "1203    1.963390  1.525764 -0.315384       -0.171436     False  ...   \n",
      "1311   -0.509323 -0.655409  3.170737       -1.191811      True  ...   \n",
      "1234   -0.509323 -0.655409 -0.315384       -0.171436     False  ...   \n",
      "725    -0.509323 -0.655409 -0.315384       -0.171436     False  ...   \n",
      "\n",
      "      Type_Occupation_Laborers  Type_Occupation_Low-skill Laborers  \\\n",
      "1545                     False                               False   \n",
      "1203                      True                               False   \n",
      "1311                      True                               False   \n",
      "1234                      True                               False   \n",
      "725                       True                               False   \n",
      "\n",
      "      Type_Occupation_Managers  Type_Occupation_Medicine staff  \\\n",
      "1545                      True                           False   \n",
      "1203                     False                           False   \n",
      "1311                     False                           False   \n",
      "1234                     False                           False   \n",
      "725                      False                           False   \n",
      "\n",
      "      Type_Occupation_Private service staff  Type_Occupation_Realty agents  \\\n",
      "1545                                  False                          False   \n",
      "1203                                  False                          False   \n",
      "1311                                  False                          False   \n",
      "1234                                  False                          False   \n",
      "725                                   False                          False   \n",
      "\n",
      "      Type_Occupation_Sales staff  Type_Occupation_Secretaries  \\\n",
      "1545                        False                        False   \n",
      "1203                        False                        False   \n",
      "1311                        False                        False   \n",
      "1234                        False                        False   \n",
      "725                         False                        False   \n",
      "\n",
      "      Type_Occupation_Security staff  Type_Occupation_Waiters/barmen staff  \n",
      "1545                           False                                 False  \n",
      "1203                           False                                 False  \n",
      "1311                           False                                 False  \n",
      "1234                           False                                 False  \n",
      "725                            False                                 False  \n",
      "\n",
      "[5 rows x 45 columns]\n"
     ]
    }
   ],
   "source": [
    "from sklearn.preprocessing import StandardScaler\n",
    "\n",
    "# Identify numerical columns (excluding boolean columns which resulted from one-hot encoding)\n",
    "numerical_cols = X_train.select_dtypes(include=['int64', 'float64']).columns\n",
    "\n",
    "# Initialize StandardScaler\n",
    "scaler = StandardScaler()\n",
    "\n",
    "# Fit on training data and transform both training and testing data\n",
    "X_train[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])\n",
    "X_test[numerical_cols] = scaler.transform(X_test[numerical_cols])\n",
    "\n",
    "print(\"X_train head after scaling numerical features:\")\n",
    "print(X_train.head())\n",
    "print(\"\\nX_test head after scaling numerical features:\")\n",
    "print(X_test.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "executionInfo": {
     "elapsed": 491,
     "status": "ok",
     "timestamp": 1771059670540,
     "user": {
      "displayName": "MANISH SINGHAL",
      "userId": "13178962604892332050"
     },
     "user_tz": -330
    },
    "id": "VGKwzY58YJcI",
    "outputId": "c7b4604e-30c3-4349-be0f-2fdf171ffed7"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "--- XGBoost Classifier Metrics ---\n",
      "Accuracy: 0.9129\n",
      "AUC Score: 0.8160\n",
      "Precision: 0.6667\n",
      "Recall: 0.4571\n",
      "F1 Score: 0.5424\n",
      "Matthews Correlation Coefficient (MCC): 0.5069\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [09:01:08] WARNING: /workspace/src/learner.cc:790: \n",
      "Parameters: { \"use_label_encoder\" } are not used.\n",
      "\n",
      "  bst.update(dtrain, iteration=i, fobj=obj)\n"
     ]
    }
   ],
   "source": [
    "from xgboost import XGBClassifier\n",
    "from sklearn.metrics import accuracy_score, roc_auc_score, precision_score, recall_score, f1_score, matthews_corrcoef\n",
    "\n",
    "# Initialize the XGBoost Classifier\n",
    "# Using a random_state for reproducibility\n",
    "# Using default parameters for initial model, can be tuned later if needed\n",
    "xgb_model = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss')\n",
    "\n",
    "# Train the model\n",
    "xgb_model.fit(X_train, y_train)\n",
    "\n",
    "# Make predictions on the test set\n",
    "y_pred_xgb = xgb_model.predict(X_test)\n",
    "y_pred_proba_xgb = xgb_model.predict_proba(X_test)[:, 1] # Probability of the positive class\n",
    "\n",
    "# Calculate evaluation metrics\n",
    "accuracy_xgb = accuracy_score(y_test, y_pred_xgb)\n",
    "auc_score_xgb = roc_auc_score(y_test, y_pred_proba_xgb)\n",
    "precision_xgb = precision_score(y_test, y_pred_xgb, zero_division=0)\n",
    "recall_xgb = recall_score(y_test, y_pred_xgb)\n",
    "f1_xgb = f1_score(y_test, y_pred_xgb)\n",
    "mcc_xgb = matthews_corrcoef(y_test, y_pred_xgb)\n",
    "\n",
    "# Print the metrics\n",
    "print(\"\\n--- XGBoost Classifier Metrics ---\")\n",
    "print(f\"Accuracy: {accuracy_xgb:.4f}\")\n",
    "print(f\"AUC Score: {auc_score_xgb:.4f}\")\n",
    "print(f\"Precision: {precision_xgb:.4f}\")\n",
    "print(f\"Recall: {recall_xgb:.4f}\")\n",
    "print(f\"F1 Score: {f1_xgb:.4f}\")\n",
    "print(f\"Matthews Correlation Coefficient (MCC): {mcc_xgb:.4f}\")"
   ]
  }
 ],
 "metadata": {
  "colab": {
   "authorship_tag": "ABX9TyN5GpUd7AfkqbbczVbEauL9",
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
